base_path: '.'

files:
  
  # --- First File Group: FRONTEND ---
  - source: '/frontend/public/locales/en/translation.json'
    translation: '/frontend/public/locales/%language_code%/translation.json'
